# Generated by Django 4.2.18 on 2025-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('local', 'Local Payment')], max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات بوابة الدفع',
                'verbose_name_plural': 'إعدادات بوابات الدفع',
            },
        ),
    ]
