# Generated by Django 5.2.8 on 2025-11-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0002_subscriptionplan_paymentgatewayconfig_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.organization'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trainer_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
